- lua/easy-dotnet/parsers/sln-parse.lua
When parsing the sln file it picks up other non-projects like e.g "Tests", "Solution Items" etc.. These are sort of groupings defined in the sln file but of no interest when performing any of the actions
> feat: filter out non projects from sln

- README.md
- lua/easy-dotnet/options.lua
Fixes an error where the `dotnet build` command would not run correctly using the default readme configuration
> fix: terminal commands not executing correctly

- README.md
- lua/easy-dotnet/test-runner/keymaps.lua
Add a keymap for running all tests independent of which test is focused. Nice for when a test does not belong to a namespace.
Improves the issues mentioned in #33
> feat: add <leader>R for running all tests

- lua/easy-dotnet/test-runner/runner.lua
Prevent rerunning dotnet test discover if an existing buffer is reused
Fixes: #40
> fix: no refresh when reopening buffer

- README.md
- lua/easy-dotnet/test-runner/keymaps.lua
- lua/easy-dotnet/test-runner/render.lua
- lua/easy-dotnet/test-runner/runner.lua
Added keymap `<leader>fe` to filter only failed testruns, requires atleast one failed test to be present and removes inconclusive, passed and skipped tests
Fixes: #36
> feat(testrunner): toggle failed tests

- lua/easy-dotnet/debugger.lua
BREAKING CHANGE: The `get_environment_variables` function has been refactored, which introduces a breaking change.
It now takes a second argument project_path. This is to ensure the correct launchsettings.json file is picked.
```lua
local dll = ensure_dll()
local vars = dotnet.get_environment_variables(dll.project_name, dll.relative_project_path)
```
> fix!: get_environment_variables picking wrong launchsettings file

- README.md
- lua/easy-dotnet/init.lua
Adds a dotnet.is_dotnet_project() function to check whether cwd or its subfolders contain a csproject or sln file
fixes: #70
> feat: add is_dotnet_project() function

- README.md
- lua/easy-dotnet/actions/build.lua
- lua/easy-dotnet/actions/restore.lua
- lua/easy-dotnet/constants.lua
- lua/easy-dotnet/debug.lua
- lua/easy-dotnet/default-manager.lua
- lua/easy-dotnet/options.lua
- lua/easy-dotnet/outdated/outdated.lua
- lua/easy-dotnet/test-runner/keymaps.lua
- lua/easy-dotnet/test-runner/render.lua
- lua/easy-dotnet/test-runner/runner.lua
- lua/easy-dotnet/test-runner/test-parser.lua
- lua/easy-dotnet/test-runner/window.lua
Trying to give the testrunner a cleaner look, today its very "distracting". I want to use more subtle higlight groups and make it intuitive without explicitly spamming "❌" emojis etc..
Features
Issues
When running dotnet test on the solution it seems hard to differentiate which tests belongs to which project, solved for now by just running a for loop on the projects in the solution and running in parallel. Uncertain which consequences this will have
Initially when testing on a rather small group of tests in a project I ran into memory issues when using vim.fn.json_decode on the converted json. I modified the F# script to remove a lot of unused fields from the outputted json, but I can still imagine that a csproject could potentially have 1000+ tests. Which is guaranteed to crash the …
> feat(testrunner): v2 testrunner

- lua/easy-dotnet/parsers/csproj-parse.lua
- lua/easy-dotnet/parsers/sln-parse.lua
Add bin and dll path directly on the project.
Could potentially ensure both the dir and dll exists to emit build missing warnings
> feat: extend csproj parser

- lua/easy-dotnet/init.lua
I ran into a problem when setting everything up for the first time where I couldn't open the test runner. This commit fixes that issue
> Fixed issue running testrunner when opts is not set

- README.md
- lua/easy-dotnet/init.lua
- lua/easy-dotnet/options.lua
- lua/easy-dotnet/test-runner/discovery.lua
- lua/easy-dotnet/test-runner/keymaps.lua
- lua/easy-dotnet/test-runner/runner.lua
- lua/easy-dotnet/test-runner/test-parser.lua
Uses vstest and F# instead of `dotnet test -t` for test discovery, this fixes a lot of bugs and brings a lot of enhancements.
> feat(testrunner): test discovery using vstest native code

- lua/easy-dotnet/actions/build.lua
- lua/easy-dotnet/actions/clean.lua
- lua/easy-dotnet/actions/new.lua
- lua/easy-dotnet/actions/restore.lua
- lua/easy-dotnet/actions/run.lua
- lua/easy-dotnet/actions/test.lua
- lua/easy-dotnet/default-manager.lua
- lua/easy-dotnet/init.lua
- lua/easy-dotnet/parsers/csproj-parse.lua
- lua/easy-dotnet/parsers/sln-parse.lua
- lua/easy-dotnet/secrets.lua
- lua/easy-dotnet/test-runner/runner.lua
> feat: basic F# support

- lua/easy-dotnet/actions/new.lua
Dotnet new would fail to create a new project if no solution file present
> fix(dotnet new): unable to create project if no solution file

- lua/easy-dotnet/debugger.lua
- lua/easy-dotnet/default-manager.lua
- lua/easy-dotnet/parsers/csproj-parse.lua
- lua/easy-dotnet/test-runner/runner.lua
Changed the logic regarding dotnet version for a specific project, this property can be set using MSBuild configurations.
Version in the `DotnetProject` class is now `string|nil`. 
The `dll_path` field is removed in favor of the `get_dll_path` this is due to having to call dotnet msbuild command to get the output path.
This is safer because the previous dll_path was a best guess whilst this is more of a guaranteed path
> feat: use msbuild for project version

- README.md
- lua/easy-dotnet/async-utils.lua
- lua/easy-dotnet/options.lua
- lua/easy-dotnet/test-runner/keymaps.lua
- lua/easy-dotnet/test-runner/runner.lua
Will add the option to pass `--no-build` and `--no-restore` using the properties `noBuild` and `noRestore` in the test_runner options section
> add restore, build for testrunner

- lua/easy-dotnet/debugger.lua
- lua/easy-dotnet/init.lua
Adds experimental support for debugging unit tests. This functionality relies on `dotnet test --environment=VSTEST_HOST_DEBUG=1`. Tested on basic test projects and seems to work great so far. Not sure about environment variables yet.
> feat: add experimental support for debugging unit tests

- README.md
- lua/easy-dotnet/actions/build.lua
- lua/easy-dotnet/actions/run.lua
- lua/easy-dotnet/actions/test.lua
- lua/easy-dotnet/init.lua
- lua/easy-dotnet/options.lua
Will allow users to call `Dotnet build release` which in turn will result in `dotnet build -c release`. I intentionally do not blindly allow args and will add sensible commands. If calling `Dotnet build -c release` then whats the point of abstractions? I might expose a raw arg at some point. We'll see
This PR requires changes for those who have set the terminal option in their call to the setup function. Otherwise args will not be propagated.
> feat: add support for extra args in Dotnet build|test|run

- README.md
- lua/easy-dotnet/ef-core/database.lua
- lua/easy-dotnet/ef-core/dbcontext.lua
- lua/easy-dotnet/ef-core/migration.lua
- lua/easy-dotnet/ef-core/utils.lua
- lua/easy-dotnet/init.lua
Partly implements: #85 
Trying to make a basic ef core abstraction to utilize the project picker for picking startup-project and project
Will test it out for now and probably add some sort of default manager in the future. Selecting project and startup project is tedious but I think it will be impossible to programatically resolve if startup project is needed.
Does not support multiple db contexts yet.
> feat(ef): add ef core integration

- README.md
- lua/easy-dotnet/actions/run.lua
- lua/easy-dotnet/init.lua
Allows for certain arguments to pass through the `Dotnet run|test|build` commands
Examples:
- `Dotnet build release`
- `Dotnet run release --no-build`
- `Dotnet test release --no-build --no-restore`
- `Dotnet run -c prerelease`
Improves: #87
> feat: allow more arguments to fallthrough from Dotnet commands

- README.md
- lua/easy-dotnet/actions/build.lua
- lua/easy-dotnet/actions/restore.lua
- lua/easy-dotnet/actions/test.lua
- lua/easy-dotnet/ef-core/database.lua
- lua/easy-dotnet/ui-modules/spinner.lua
Using string format with the %s will cause nil to be interpreted literally.
This resulted in some commands being called with nil argument, propagating into the terminal command and causing it to fail.
> fix(term): some term commands concatenated nil causing command to fail

- README.md
- lua/easy-dotnet/csproj-mappings.lua
- lua/easy-dotnet/init.lua
Adds autocomplete to `<PackageReference Include="<here>" Version="<here>"`.
This relies on `dotnet package search` and `jq`
Partly implements: #124
> feat(cmp): add package autocomplete

- README.md
- lua/easy-dotnet/debugger.lua
- lua/easy-dotnet/test-runner/keymaps.lua
Testing out being able to start the nvim-dap debugger directly from the testrunner with keybind `<leader>d`
This will do the following
1. Close testrunner
2. Open selected testfile
3. Set breakpoint on the first line in the function
4. Dynamically register a dap config for this test
5. profit???
https://github.com/user-attachments/assets/b56891c9-1b65-4522-8057-43eff3d1102d
> feat(testrunner):🧪🎁 keybind to debug test using nvim-dap

- lua/easy-dotnet/cs-mappings.lua
Fixes an issue where the auto bootstrap namespace function freezes. Set a max depth to 10 to prevent infinite cycling
> fix:🐛 auto bootstrap namespace freezing

- lua/easy-dotnet/outdated/outdated.lua
Made a debug notification instead of crashing as `dotnet outdated` will also pull packages from the `Directory.Packages.props` file. 
Thus it will be very understanding that the plugin cannot find the package in the csproj.
> fix: dont crash on missing package 🐛

- README.md
- lua/easy-dotnet/actions/run.lua
Fixed a bug where `run_with_profile` would crash if no launchSettings.json file is found
> fix:🐛 launch_with_profile crash on no launchSettings file

- lua/easy-dotnet/options.lua
- lua/easy-dotnet/outdated/outdated.lua
- lua/easy-dotnet/test-runner/keymaps.lua
- lua/easy-dotnet/test-runner/runner.lua
- lua/easy-dotnet/test-runner/test-parser.lua
improvement for windows support:
* normalization of paths obtained via nvim api to always use `/`, which is supported in both linux and windows.
* removal of quotes where not really needed
- exception for `dotnet test ... --logger="trx;logFileName=%s"` where using double quotes  is the only option supported by both linux and windows
> fix:🐛 windows path parsing

- lua/easy-dotnet/test-runner/test-parser.lua
Hi, after the #164 fix, another issue has arisen. If you take the repro from the linked issue and replace `dotnet8` with `dotnet5` (you should replace `ClassicAssert` with `Assert` as well), there will be another error in the F# script:
```
test_parser.fsx(19,5): error FS0041: No overloads match for method 'Item'.
Known types of arguments: string * string
Available overloads:
- JObject.set_Item(propertyName: string, value: JToken) : unit // Argument 'value' doesn't match
- JToken.set_Item(key: obj, value: JToken) : unit // Argument 'value' doesn't match
```
My installed SDKs are:
```
5.0.408
8.0.303
```
So, on `dotnet5`, `JObject` can accept only `JValue`, while on `dotnet8` it also accepts `String`. It was a minor refactoring, so let's revert this line so the script can work on both …
> Testrunner fix for dotnet 5

- README.md
- lua/easy-dotnet/actions/new.lua
- lua/easy-dotnet/init.lua
Code and example for integrating `dotnet new` into nvim-tree, oil.nvim etc.. 
Will allow for creating api controllers, solution files, web.config etc from the tree
nvim-tree code
```lua
vim.keymap.set('n', 'A', function()
local node = api.tree.get_node_under_cursor()
local path = node.type == "directory" and node.absolute_path or vim.fs.dirname(node.absolute_path)
require("easy-dotnet").create_new_item(path)
end, opts('Create file from dotnet template'))
```
> feat(dotnet new):🎁 nvim-tree integration

- lua/easy-dotnet/test-runner/runner.lua
seems to be a typo here, because the field with the correct name `collapsable` is set below
> chore: remove unused code

- README.md
- lua/easy-dotnet/test-runner/keymaps.lua
- lua/easy-dotnet/test-runner/test-parser.lua
Previously the stacktrace was shown but not the message. With this change the stacktrace should be easier to read because it tells you which validation failed. 
- Trimmed leading whitespace making the stacktrace harder to read
- Added message to top of stacktrace making it more understandable
```diff
+ Assert.True() Failure
+ Expected: True
+ Actual:   False
+ at NeovimDebugProject.IntegrationTests.Services.MathServiceTests.Add_ShouldHandleLargeNumbers() in C:\Users\Gustav\repo\NeovimDebugProject\src\NeovimDebugProject.IntegrationTests\Services\MathServiceTests.cs:line 17
+ at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
+ at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
-    at …
```
> feat(testrunner):🎁 improve stacktrace

- lua/easy-dotnet/test-runner/render.lua
Fixed multiple errors with `viewmode: buf` for testrunner
- Toggling testrunner will result in an error if no previous buffer exists
- Height will be set in buffer mode making the buffer smaller than necessary
> fix(testrunner): buffer mode errors

- lua/easy-dotnet/test-runner/keymaps.lua
When using Expecto F# test framework a test will produce an xml file similiar to the other test frameworks. If the test fails there will be noe stacktrace node, rather it is included in the message
The code used to assume that the stacktrace property will always be populated if the test failed. This is not the case
```xml
<Output>
<ErrorInfo>
<Message>
These should equal. String does not match at position 4. Expected char: 'e', but got 'ë'.
expected: abcdef
actual: abcdëf
at Tests.tests@30-6.Invoke(Unit _arg7) in NeovimDebugProject.Expecto\Sample.fs:line 31&#xD;
at Expecto.Impl.execTestAsync@569-1.Invoke(Unit unitVar)&#xD;
at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in …
```
> fix(testrunner): stacktrace undefined using Expecto

- lua/easy-dotnet/test-runner/keymaps.lua
Previously we used the stacktrace to get the file path and line number. This was done using lua string matching. We now use TranslationLayer and can get the filepath from there as structured data. This is more reliable and less error prone.
Fixes: #184
> fix(testrunner): stack trace filepath

- lua/easy-dotnet/commands.lua
Previously I was careful with allowing additional args to `dotnet build|run|test` but given my new setup with commands it wont be an issue. Opening up the implementation so that any argument can be passed through. Subcommands will always take precedence over args
> feat:🎁 passing any dotnet argument to `Dotnet run|test|build`

- lua/easy-dotnet/health.lua
fixes a bug where checking for cli deps would cause the health check to error without proceeding. This was due to vim.fn.system erroring when invoking an unknown command. Fixed by wrapping in pcall
> fix:🐛 healthcheck pcall

- lua/easy-dotnet/test-runner/keymaps.lua
- lua/easy-dotnet/test-runner/render.lua
- lua/easy-dotnet/test-runner/runner.lua
- lua/easy-dotnet/test-runner/test-parser.lua
> feat(testrunner):🎁 add duration to test runs

- lua/easy-dotnet/commands.lua
- lua/easy-dotnet/nuget.lua
Allows searching for nuget packages with an initial search term. Like `Dotnet add package Newtonsoft`, which will automatically open the telescope search with the prompt Newtonsoft
> feat(nuget):🎁 support initial search term from vim cmd

- lua/easy-dotnet/picker/_base.lua
- lua/easy-dotnet/picker/init.lua
Migration picker is missing for telescope. 
My bad, I missed to add it in the check function.
> add migration picker for telescope

- lua/easy-dotnet/completion/blink.lua
I deleted the fork too early, and the other PR was closed
> Add blink.cmp support for "latest" snippet

- README.md
- lua/easy-dotnet/options.lua
- lua/easy-dotnet/picker/init.lua
Hi!
I recently changed my default picker from telescope to fzf-lua. Within the plugin, the transition was not so smooth: after disabling telescope I started getting the message “config.picker is set to telescope but telescope is not installed. Using basic picker”. That is, I got the basic picker even though I had fzf-lua installed.
I suggest adding automatic detection of available picker (Telescope or fzf-lua) with fallback to basic picker.
Implemented it like this:
In options, the default value for the picker is now `nil`, which triggers the automatic detection of the available picker in this order: Telescope -> fzf-lua -> basic. If a specific picker is given, then it is used.
> feat: auto selection for picker

- lua/easy-dotnet/project-view/render.lua
Simple fix for a bug that caused the `project-view` window keymaps to be set globally instead of to the `project-view` buffer.
> fix(project-view): keymaps being set globally instead of locally

- lua/easy-dotnet/test-runner/runner.lua
Reopening testrunner buffer fails sometimes giving errror: 
```
Coroutine failed: .../easy-dotnet.nvim/lua/easy-dotnet/test-runner/runner.lua:356: vim/keymap.lua:0: Invalid buffer id: 127
```
No idea why. An extra check if the last used testrunner buffer is still valid should fix the problem.
> fix: testrunner invalid buffer

- lua/easy-dotnet/cs-mappings.lua
Currently, if you add a file from netrw (press %, type the name, open it), the automatic namespace bootstrapping doesn't happen. To solve this, I added BufNewFile to the autocmd to make it trigger when opening completely new files.
> fix: add BufNewFile to auto_bootstrap_namespace autocmd

- lua/easy-dotnet/parsers/csproj-parse.lua
- lua/easy-dotnet/project-view/render.lua
Added worker project type. Worker projects are also runnable so should also work with Dotnet run.
First Pr here, happy for any feedback. Used _nf-cod-server_process_ as icon for worker. p.s is nvim-web-devicons a requirement for this plugin?
> feat: add worker project type

- lua/easy-dotnet/health.lua
#294 seemed to brake the helthcheck on mac. 
@GustavEikaas could you try if this one works on Windows. I can test on Linux later.
> fix: healthcheck for `dotnet-ef`, `dotnet outdated` not working on all os's

- .luacheckrc
- lua/easy-dotnet/completion/blink.lua
Fix for an error that prints `failed to get completions with error: ...zy/easy-dotnet.nvim/lua/easy-dotnet/completion/blink.lua:18: attempt to call upvalue 'callback' (a table value)` when entering insert mode on an xml, csproj or fsproj file. This error makes blink completion stop working.
This error was introduced in commit f23ca5f due to luacheck marking the methods with warning 212 `unused argument self` and fixing the warning by converting the methods to functions. This could be fixed by either using comments to ignore the lines in the file:
```lua
-- luacheck: push no unused args
function M:get_completions(ctx, callback) ... end
-- ...
-- luacheck: pop
```
or by ignoring it globally for the `self` argument in `.luacheckrc`:
```lua
ignore = { "212/self" }
```
With the latter approach …
> fix(completion): 'failed to get completions' with blink.cmp

- lua/easy-dotnet/health.lua
- lua/easy-dotnet/options.lua
I have gotten more why isnt this working issues lately and I find myself requesting the same info every time.Extending the healthcheck will hopefully make it easier to check the 'usual suspects' without having to ask every user for it
@bosvik thoughts? Something useful I might have missed?
This will add following
- Neovim version
- OS platform info
- Dotnet version
- Dotnet sdks
- Sdk path 
- User plugin config (before merge)
- Shell info
> feat: improve healthcheck

- lua/easy-dotnet/parsers/csproj-parse.lua
Actually I was trying to fix the absence of most projects in the picker window when selecting the option for debugging. After adding WinExe support everything started working great
> feat: add project type WinExe support

- lua/easy-dotnet/dotnet_cli.lua
`solution` is not a verb for the dotnet cli. Using sln so it can actually find projects in a solution.
> Use dotnet sln instead of dotnet solution since the later does not exist

- lua/easy-dotnet/debugger.lua
- lua/easy-dotnet/picker/_base.lua
- lua/easy-dotnet/picker/_fzf.lua
- lua/easy-dotnet/picker/_snacks.lua
- lua/easy-dotnet/picker/_telescope.lua
- lua/easy-dotnet/picker/init.lua
This feature makes it easier to quickly select item from the list.
I used it for the debug projects list:
> Add numbering to picker and use it for debug projects list

- lua/easy-dotnet/extensions.lua
- lua/easy-dotnet/test-runner/runner.lua
MacOS uses non standard folders as tmp. This fix adds the macOS folder to the path lookup when the server starts
> fix: resolve testrunner pipe path on macos

- lua/easy-dotnet/init.lua
- lua/easy-dotnet/parsers/sln-parse.lua
Previously background scanning would cache all msbuild properties. This gave a huge perf boost. With the introduction of #356 I forgot to extend the background scanning. When calling on `get_projects_from_sln` it would call `dotnet sln x list` synchronously. On windows this causes about ~1.7s lag in a "normal" project.
With this change the background scanning is extended to call `get_projects_from_sln_async`. With background scanning enabled windows users will se a performance diff of `~1.7s` when calling any command that invokes `get_projects_from_sln` for the first time during a session
> feat: background scanning preloading sln projects

- lua/easy-dotnet/constants.lua
- lua/easy-dotnet/init.lua
- lua/easy-dotnet/test-signs.lua
First of all, this plugin is amazing. Thank you Gustav.
Ok so the goal of this is to be able to run tests in buffer with the cursor somewhere inside the wanted test method instead of having to be on the method line itself. This makes the run-in-buffer much easier to use.
Also added the gutter sign with the already configured `reload` sign so we get visual feedback.
This can be changed and improved upon, also not sure if adding the require on treesitter is a deal breaker?
> feat(buffer test execution): run tests with cursor anywhere inside method declaration

- lua/easy-dotnet/test-runner/render.lua
> fix(testrunner): vim.keymap.set failing on invalid buffer

- lua/easy-dotnet/outdated/outdated.lua
When doing `:Dotnet outdated` in my directory.packages.props, a warning appears informing that the Magick.NET-Q8-AnyCPU nuget is not found on the file.
Looks like the code was escaping dots `.` but not hypens `-` in the package name.
This PR adds the hypen as a escaped character, since the lua match takes those as regex special characters.
When doing `:Dotnet outdated` in my `directory.packages.props`, a warning appears informing that the **Magick.NET-Q8-AnyCPU nuget** is not found on the file.
Looks like the code was escaping dots `.` but not hyphens `-` in the package name. 
This PR adds the hyphen as an escaped character.
> fix(dotnet outdated): escape `-` in package names

- README.md
- lua/easy-dotnet/outdated/outdated.lua
Adds support for dotnet outdated for the file Directory.Build.Props. 
I've copied the block from the solution-scoped files (directory.packages.props and packages.props) but used the PATTERN_TYPE_REFERENCE.
> feat(dotnet-outdated): Add support for Directory.Build.Props in dotnet outdated

- lua/easy-dotnet/completion/blink.lua
- lua/easy-dotnet/csproj-mappings.lua
- lua/easy-dotnet/nuget.lua
- lua/easy-dotnet/project-view/render.lua
hey @GustavEikaas 
Thanks for the great plugin
For cmd in windows, jq seems only supports double quotes.
Double quotes are working fine in linux and Powershell too, not sure about mac though, as I don't have a mac to test against.
Thanks
> fix: windows (cmd) jq argument quotes

- README.md
- lua/easy-dotnet/init.lua
- lua/easy-dotnet/test-signs.lua
Quick-fix for #399.
I only tested with LazyVim on macOS.
> Use nvim_set_buf_extmark instead of sign_place

- README.md
- lua/easy-dotnet/actions/new.lua
- lua/easy-dotnet/init.lua
During integration with snacks.explorer I noticed that callback passed to `create_new_item` function is not executed. As it turned out the `wrap` function was only passing first argument to coroutine.
Right now, the callback also receives the path of the created item (so in the case of `snacks.explorer`, the newly created file is focused). I’ve extended the logic a bit so that the user is not always prompted for a file name, since not all templates support this.
Since I am quite new to lua/neovim api, I am open to any suggestions and criticism!
Commits:
- Pass all arguments to coroutine
- Add snacks.explorer integration example
- Determine if input prompt is needed
- Pass created item path to callback
> feat: snacks.explorer integration

- lua/easy-dotnet/options.lua
- lua/easy-dotnet/rpc/dotnet-client.lua
- lua/easy-dotnet/rpc/rpc-client.lua
Helps with recieving large responses like build errors and build warnings. Lets you enumerate arbitrary properties within rpc response
> feat: rpc nuget restore

- README.md
- lua/easy-dotnet/actions/diagnostics.lua
- lua/easy-dotnet/commands.lua
- lua/easy-dotnet/diagnostics.lua
- lua/easy-dotnet/init.lua
- lua/easy-dotnet/options.lua
- lua/easy-dotnet/rpc/dotnet-client.lua
Add workspace diagnostics functionality to get compilation
errors and warnings from entire solutions or individual projects.
- Add Dotnet diagnostic error/warning commands
- Integrate with Roslyn LSP for cross-file diagnostic refresh
- Populate diagnostics into Neovim's diagnostic system
- Support both project and solution-level analysis
Commands:
- Dotnet diagnostic error (errors only)
- Dotnet diagnostic warning (errors + warnings)
API: dotnet.diagnostics.get_workspace_diagnostics(severity_filter)
Depends on GustavEikaas/easy-dotnet-server#92
> feat: add workspace diagnostics support

- lua/easy-dotnet/parsers/sln-parse.lua
- lua/easy-dotnet/rpc/dotnet-client.lua
- lua/easy-dotnet/rpc/rpc-client.lua
When server fails for whatever reason some jobs just hang indefinitely. Like query project properties and initializing. This PR fixes that
> fix(rpc): hanging jobs when server fails

- lua/easy-dotnet/options.lua
Fixes an issue where extra args to cli commands were not being passed, example `--launch-profile x`
> fix: extra dotnet cli args not being passed

- lua/easy-dotnet/completion/blink.lua
- lua/easy-dotnet/csproj-mappings.lua
- lua/easy-dotnet/rpc/dotnet-client.lua
When searching for nuget packages/nuget package versions it would automatically cancel in-flight requests limiting concurrency to 1. client code did not cleanup the jobs that were being cancelled causing them to pile up and spin forever
> fix: cleanup cancelled jobs
