- README.md
- lua/easy-dotnet/init.lua
- lua/easy-dotnet/options.lua
- lua/easy-dotnet/test-runner/keymaps.lua
- lua/easy-dotnet/test-runner/render.lua
- lua/easy-dotnet/test-runner/runner.lua
> feat: test runner

- README.md
- lua/easy-dotnet/constants.lua
- lua/easy-dotnet/init.lua
- lua/easy-dotnet/outdated/outdated.lua
> feat: add outdated command, virtual text

- lua/easy-dotnet/parsers/sln-parse.lua
> fix: relative path conversion for sln parser (linux support)

- README.md
Add some advanced examples to the readme
> docs: add advanced configurations to the readme

- README.md
- lua/easy-dotnet/actions/clean.lua
- lua/easy-dotnet/init.lua
Adding the dotnet clean command
> feat(clean): add dotnet clean command

- lua/easy-dotnet/parsers/csproj-parse.lua
Added more checks to ensure all test projects are found
Fixes #56
> fix(test): not discovering all test projects

- lua/easy-dotnet/outdated/outdated.lua
Currently the Outdated command may use the results of the wrong project as it is currently using the first one. It is easily reproducible , if you have a main project and an other one for tests and the test project references the main one (as usual) you will get the error in case the main project has outdated dependencies and run Outdated on the test project.
This PR changes that so the one with the same name as the csproj file is used (if exists).
> fix(outdated): reading dependencies from wrong project

- lua/easy-dotnet/test-runner/render.lua
I ran into an issue with a key mapping I had set for <leader>fe no longer working after using the test runner. It looked like the test runner was trying to set the keymaps before the buffer id was set causing the key mappings to not be set to the buffer
This change right now just affects the test runner as it's the only place setMappings() is being called
I wasn't sure if the window should have rendered first before calling set keymaps but this change would make it so the order does not matter
> fix: issue with test runner not setting keymapping to local buffer

- README.md
- lua/easy-dotnet/options.lua
- lua/easy-dotnet/test-runner/keymaps.lua
- lua/easy-dotnet/test-runner/render.lua
- lua/easy-dotnet/test-runner/runner.lua
- lua/easy-dotnet/test-runner/test-parser.lua
> feat(testrunner): different viewmodes split/float/buf

- lua/easy-dotnet/parsers/sln-parse.lua
> fix(sln-parse): rel path unix bug

- lua/easy-dotnet/options.lua
Only append `\r` if is windows machine
Fixes:
#108
> fix(term): default options not linux compatible

- lua/easy-dotnet/test-runner/keymaps.lua
- lua/easy-dotnet/test-runner/render.lua
- lua/easy-dotnet/test-runner/runner.lua
- lua/easy-dotnet/test-runner/test-parser.lua
This PR will add a task status in the top right corner of the testrunner as virtual text. Showing how many tests it is currently running and how many tests have completed
> feat(testrunner): virtual text status top right corner

- lua/easy-dotnet/actions/build.lua
Fixes an issue where a user could call `dotnet_build_quickfix` multiple times in a row which would result in builds failing due to file locks
> fix: disallow concurrent builds

- lua/easy-dotnet/cs-mappings.lua
Consider adding some info to the readme about this.
In the future add support for templates
> feat: auto bootstrap interface

- stylua.toml
Just a small stylua settings file you can take if you want.
It helps collaboration if the repo contains rules for the formatting such that my tool wont mess up any formatting for you :) 
Awesome plugin. Thank you very much
> chore: added stylua settings

- README.md
- lua/easy-dotnet/actions/init.lua
- lua/easy-dotnet/actions/run.lua
- lua/easy-dotnet/default-manager.lua
- lua/easy-dotnet/init.lua
- lua/easy-dotnet/picker.lua
Adds a lua function for running a project with a specific profile
```lua
require("easy-dotnet").run_with_profile(true) --use persisted choices
```
> feat:🎁 support for picking launch profiles

- lua/easy-dotnet/outdated/outdated.lua
Support for `Directory.Packages.props` and `Packages.props` files
Also fixed a bug where outdated would say all packages are up to date because of a bug in name matching
> feat(outdated):🎁 support for directory.packages.props

- README.md
- lua/easy-dotnet/fsproj-mappings.lua
- lua/easy-dotnet/init.lua
- lua/easy-dotnet/options.lua
Adding `<leader>ar` to add a project reference
> feat:🎁 add fsproj mapping for adding reference

- lua/easy-dotnet/test-runner/keymaps.lua
- lua/easy-dotnet/test-runner/render.lua
Pressing `g` on a test in the testrunner now opens the test in a new window instead of the testrunner float
> feat(testrunner):🎁 test opens in full window

- lua/easy-dotnet/parsers/csproj-parse.lua
> fix(csproj): file handlers not closing

- lua/easy-dotnet/test-runner/test-parser.lua
Please double-check this one; I'm new to F# 😅 
Closes #164
> fix(testrunner): handle duplicate testIds

- README.md
- lua/easy-dotnet/options.lua
- lua/easy-dotnet/test-signs.lua
Add the ability to debug test directly from buffer using `<leader>d`
> feat:🎁🧪 debug test from buffer

- README.md
- lua/easy-dotnet/default-manager.lua
- lua/easy-dotnet/init.lua
- lua/easy-dotnet/parsers/sln-parse.lua
- lua/easy-dotnet/test-runner/render.lua
- lua/easy-dotnet/test-runner/runner.lua
`Dotnet solution select` to pick another solution
Testrunner does register solution change
exposes
`dotnet.try_get_selected_solution()` -> `{basename: string, path: string} | nil`
> feat:🎁 multi solution support

- README.md
- lua/easy-dotnet/extensions.lua
- lua/easy-dotnet/init.lua
- lua/easy-dotnet/parsers/sln-parse.lua
- lua/easy-dotnet/picker.lua
Add vim commands with telescope pickers for selecting project
`Dotnet solution add`
`Dotnet solution remove`
> feat:🎁 dotnet solution add/remove

- README.md
- lua/easy-dotnet/actions/build.lua
- lua/easy-dotnet/actions/clean.lua
- lua/easy-dotnet/actions/restore.lua
- lua/easy-dotnet/actions/run.lua
- lua/easy-dotnet/actions/test.lua
- lua/easy-dotnet/commands.lua
- lua/easy-dotnet/init.lua
- lua/easy-dotnet/options.lua
- lua/easy-dotnet/parsers/sln-parse.lua
- lua/easy-dotnet/test-runner/keymaps.lua
- lua/easy-dotnet/test-runner/runner.lua
- `dotnet.reset()`
- `dotnet.run_profile_default()`
- `dotnet.test()`
- `dotnet.testrunner()`
- `dotnet.testrunner_refresh()`
- `dotnet.testrunner_refresh_build()`
- `dotnet.new()`
- `dotnet.outdated()`
- `dotnet.solution_select()`
- `dotnet.solution_add()`
- `dotnet.solution_remove()`
- `dotnet.ef_migrations_remove()`
- `dotnet.ef_migrations_add()`
- `dotnet.ef_migrations_list()`
- `dotnet.ef_database_drop()`
- `dotnet.ef_database_update()`
- `dotnet.ef_database_update_pick()`
- `dotnet.createfile(path)`
- `dotnet.build_default_quickfix()`
- `dotnet.get_environment_variables(project_name, project_path)` 
- `dotnet.is_dotnet_project()`                                 
- `dotnet.try_get_selected_solution()`                  
- `dotnet.get_debug_dll()`
- `dotnet.test_solution()`
- …
> feat:🎁 exposed lua functions and vim commands in sync🔃

- README.md
- lua/easy-dotnet/commands.lua
- lua/easy-dotnet/init.lua
- lua/easy-dotnet/nuget.lua
vim: `Dotnet add package`
lua: `dotnet.add_package()`
Gives you a telescope picker for searching nuget packages, upon selecting a a package you will be given a new picker for which version to install. Lastly you will get a picker for which project to add to
1. Search package
2. Select version
3. Select project to add to
> feat:🎁 nuget search

- README.md
- lua/easy-dotnet/health.lua
Checks
- Lua deps
- telescope
- plenary
- nvim-dap (not required)
- roslyn (not required, QOL)
- CLI deps
- jq
- dotnet
- dotnet-outdated
- dotnet-ef
- options
- get_sdk_path performance impact
- extra
- nvim dap coreclr configuration
> feat:🩺 add healthcheck

- README.md
- lua/easy-dotnet/commands.lua
- lua/easy-dotnet/csproj-mappings.lua
- lua/easy-dotnet/default-manager.lua
- lua/easy-dotnet/dotnet_cli.lua
- lua/easy-dotnet/fsproj-mappings.lua
- lua/easy-dotnet/init.lua
- lua/easy-dotnet/nuget.lua
- lua/easy-dotnet/project-view/init.lua
- lua/easy-dotnet/project-view/render.lua
Creating a project view where you can view details about a project file and its contents.
Should support the following
> feat:🎁 project view

- README.md
- lua/easy-dotnet/commands.lua
- lua/easy-dotnet/nuget.lua
**Vim**: `Dotnet remove package`
**lua**: `dotnet.remove_package()`
> feat:🎁 remove nuget package

- lua/easy-dotnet/csproj-mappings.lua
After the changes in  #212, add_project_reference was broken, fix for it
> fix:🐛csproj add_project_reference keybind

- lua/easy-dotnet/nuget.lua
There was a dependency on fzf-lua in nuget.lua making 'package add' crash if fzf-lua isn't installed
> remove dependency on fzf-lua until it makes it into optionals

- lua/easy-dotnet/picker/init.lua
> fix: correct picker check

- lua/easy-dotnet/ui-modules/spinner.lua
> add check for snacks and reuse id if snacks is installed

- lua/easy-dotnet/cs-mappings.lua
Prevents loading entire file contents into memory for checking if buffer is empty. This was affecting large files. Causing lag
> feat: namespace bootstrap performance improvement

- README.md
- lua/easy-dotnet/options.lua
- lua/easy-dotnet/picker/_snacks.lua
- lua/easy-dotnet/picker/init.lua
> feat: add snacks picker support

- lua/easy-dotnet/outdated/outdated.lua
The outdated command would not work in Directory.Packages.probs file (Global managed dependencies) because of the pattern used is different from .csproj /fsproj.
I made a small fix that changes the pattern and searches for either PackageVersion or PackageReference depending of the file.
> Fixed the outdated search pattern in Directory.Packages.probs.

- lua/easy-dotnet/health.lua
> fix: checkhealth does not work if blink.compat is configured

- lua/easy-dotnet/init.lua
Simple cmdline completion for the `Dotnet` command. It picks commands that match the cmdline arguments and narrows down the available subcommands when typing spaces.
https://github.com/user-attachments/assets/dc128e8d-79e6-4290-ab50-70c55df35521
> feat: cmdline completion

- lua/easy-dotnet/nuget.lua
- lua/easy-dotnet/picker/_fzf.lua
- lua/easy-dotnet/picker/init.lua
Yield nuget_search until package name provided.
> fix: fzf-picker for `package add` command

- lua/easy-dotnet/dotnet_cli.lua
- lua/easy-dotnet/parsers/csproj-parse.lua
- lua/easy-dotnet/parsers/sln-parse.lua
Done TODO named "Investigate using dotnet sln list command"
didn't check for slnx
> refactor: using `dotnet sln list` command for .sln and .slnx

- lua/easy-dotnet/parsers/csproj-parse.lua
- lua/easy-dotnet/test-runner/runner.lua
- Improve test project recognition
- Notify users that MTP is not supported
> feat: improve test project detection

- lua/easy-dotnet/parsers/csproj-parse.lua
- lua/easy-dotnet/test-runner/keymaps.lua
- lua/easy-dotnet/test-runner/runner.lua
> feat: multi targetframework support testrunner

- lua/easy-dotnet/picker/_base.lua
- lua/easy-dotnet/picker/_fzf.lua
- lua/easy-dotnet/picker/_snacks.lua
- lua/easy-dotnet/picker/_telescope.lua
- lua/easy-dotnet/picker/init.lua
This reverts commit b0d65216a316fb5ccfebac1654a5a127d7b43a78.
> Revert "feat: add numbering to pickers (#344)"

- lua/easy-dotnet/test-runner/render.lua
- lua/easy-dotnet/test-runner/runner.lua
- feat: flatten namespaces with only one child
- merge conflict
> feat(testrunner): collapse namespaces and sort tests

- lua/easy-dotnet/test-runner/runner.lua
> fix(testrunner): indentation issues

- lua/easy-dotnet/test-runner/runner.lua
> fix(testrunner): sdk path not assigned correctly

- README.md
- lua/easy-dotnet/options.lua
- lua/easy-dotnet/test-runner/render.lua
> feature: testrunner optional width setting

- README.md
- lua/easy-dotnet/options.lua
- lua/easy-dotnet/test-runner/render.lua
```lua
test_runner = {
viewmode = "vsplit",
vsplit_width = 70,
vsplit_pos = "topleft",
```
> feat: testrunner vsplit position

- README.md
> docs: update readme terminal example code

- lua/easy-dotnet/project-view/render.lua
Issue mentioned in #459 after merge
> fix(project-view): add package keymap missing when no packages installed

- README.md
- lua/easy-dotnet/cs-mappings.lua
- lua/easy-dotnet/options.lua
- lua/easy-dotnet/rpc/dotnet-client.lua
- lua/easy-dotnet/rpc/rpc-client.lua
Automatically parse json and convert to class when bootstrapping new files
```diff
auto_bootstrap_namespace = {
type = "block_scoped",
enabled = true,
+    json_clipboard = {
+      behavior= 'auto' | 'prompt' | 'never', -- behavior when valid json is detected
+      register= '+' -- which register to check
+    }
},
```
Even supports nested json
```cs
using System.Text.Json.Serialization;
namespace NeovimDebugProject.Web
{
public class Person
{
[JsonPropertyName("name")]
public string Name { get; set; }
[JsonPropertyName("details")]
public Details Details { get; set; }
}
public class Details
{
[JsonPropertyName("age")]
public int Age { get; set; }
[JsonPropertyName("isStudent")]
public bool IsStudent { get; set; }
}
public class G
{
[JsonPropertyName("person")]
public Person Person { …
```
> feat: paste json as code

- lua/easy-dotnet/init.lua
- lua/easy-dotnet/test-signs.lua
> feat: add get_test_results api
